// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type PowerPlant struct {
	// ID of the power plant
	ID string `json:"id"`
	// Name of the power plant
	Name string `json:"name"`
	// Latitude in degrees
	Latitude float64 `json:"latitude"`
	// Longitude in degrees
	Longitude float64 `json:"longitude"`
	// Provided forecasts from openmeteo for the weather
	WeatherForecasts []*WeatherForecast `json:"weatherForecasts"`
	// Is there precipitation at the power plant today?
	HasPrecipitationToday bool `json:"hasPrecipitationToday"`
	// Elevation of the power plant
	Elevation float64 `json:"elevation"`
}

type PowerPlantPage struct {
	Plants     []*PowerPlant `json:"plants"`
	TotalCount int           `json:"totalCount"`
	Page       int           `json:"page"`
	PageSize   int           `json:"pageSize"`
}

type Query struct {
}

type WeatherForecast struct {
	// Time of the forecast in UTC/GMT
	Time string `json:"time"`
	// Temperature (2 m) in celsius
	Temperature float64 `json:"temperature"`
	// Precipitation (rain + showers + snow) in millimeter
	Precipitation float64 `json:"precipitation"`
	// Wind Speed (10 m) in Km/h
	WindSpeed float64 `json:"windSpeed"`
	// Wind Direction (10 m) in degrees
	WindDirection float64 `json:"windDirection"`
}
