services:
  tensor-graphql:
    image: "tensor-graphql/development:latest"
    container_name: "tensor-graphql-development"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../../:/app
      - go_dir:/go
    command: |
      ./deployments/development/start.sh
    environment:
      APP_PORT: 0.0.0.0:8080
      CORS_ORIGINS: "http://localhost:3000"
      APP_ENV: development
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    container_name: tensor_db
    environment:
      - MYSQL_DATABASE=tensor
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
volumes:
  db:
    driver: local
  go_dir:
    driver: local
